# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnss_synchro.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12gnss_synchro.proto\x12\x08gnss_sdr\"\x96\x05\n\x0bGnssSynchro\x12\x0e\n\x06system\x18\x01 \x01(\t\x12\x0e\n\x06signal\x18\x02 \x01(\t\x12\x0b\n\x03prn\x18\x03 \x01(\r\x12\x12\n\nchannel_id\x18\x04 \x01(\x05\x12\x19\n\x11\x61\x63q_delay_samples\x18\x05 \x01(\x01\x12\x16\n\x0e\x61\x63q_doppler_hz\x18\x06 \x01(\x01\x12\x1f\n\x17\x61\x63q_samplestamp_samples\x18\x07 \x01(\x04\x12\x18\n\x10\x61\x63q_doppler_step\x18\x08 \x01(\r\x12\x1e\n\x16\x66lag_valid_acquisition\x18\t \x01(\x08\x12\n\n\x02\x66s\x18\n \x01(\x03\x12\x10\n\x08prompt_i\x18\x0b \x01(\x01\x12\x10\n\x08prompt_q\x18\x0c \x01(\x01\x12\x11\n\tcn0_db_hz\x18\r \x01(\x01\x12\x1a\n\x12\x63\x61rrier_doppler_hz\x18\x0e \x01(\x01\x12\x1a\n\x12\x63\x61rrier_phase_rads\x18\x0f \x01(\x01\x12\x1a\n\x12\x63ode_phase_samples\x18\x10 \x01(\x01\x12\x1f\n\x17tracking_sample_counter\x18\x11 \x01(\x04\x12 \n\x18\x66lag_valid_symbol_output\x18\x12 \x01(\x08\x12\x1d\n\x15\x63orrelation_length_ms\x18\x13 \x01(\x05\x12\x17\n\x0f\x66lag_valid_word\x18\x14 \x01(\x08\x12 \n\x18tow_at_current_symbol_ms\x18\x15 \x01(\r\x12\x15\n\rpseudorange_m\x18\x16 \x01(\x01\x12\x0f\n\x07rx_time\x18\x17 \x01(\x01\x12\x1e\n\x16\x66lag_valid_pseudorange\x18\x18 \x01(\x08\x12\x15\n\rinterp_tow_ms\x18\x19 \x01(\x01\x12%\n\x1d\x66lag_PLL_180_deg_phase_locked\x18\x1a \x01(\x08\"8\n\x0bObservables\x12)\n\nobservable\x18\x01 \x03(\x0b\x32\x15.gnss_sdr.GnssSynchrob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gnss_synchro_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GNSSSYNCHRO._serialized_start=33
  _GNSSSYNCHRO._serialized_end=695
  _OBSERVABLES._serialized_start=697
  _OBSERVABLES._serialized_end=753
# @@protoc_insertion_point(module_scope)
