#!/usr/bin/env python3
"""
iridium_tx_libresdr.py — Transmit authentic Iridium IRA bursts via LibreSDR (Zynq7020 + AD9363)

Uses pyadi-iio to configure the AD9363 and transmit π/4-DQPSK IRA bursts
generated by iridium/realistic_sim.py (faithful Iridium parameters).

Hardware: LibreSDR (Zynq7020 + AD9363) @ ip:192.168.1.10

Signal parameters (authentic Iridium IRA):
  Modulation    : π/4-DQPSK
  Symbol rate   : 25 000 sps
  RRC roll-off  : β = 0.4  (matches gr-iridium)
  Burst structure: 64 preamble + 12 UW + 167 data + 2 tail symbols
  Preamble tone : +3125 Hz above carrier (Rs/8), detectable by gr-iridium
  TDMA frame    : 1 slot per 90 ms (Ring Alert simplex channel)

Default frequency: 868.1 MHz (ISM band) for lab tests at 868 MHz.
For field use at actual Iridium frequency: --freq 1626270000
WARNING: transmitting at 1616-1626 MHz without a licence is ILLEGAL.
         Use ISM band (868 / 433 MHz) or a wired test bench.

Dependencies:
  pip install pyadi-iio scipy numpy

Usage:
  python3 iridium_tx_libresdr.py                          # 868.1 MHz, 4 bursts then stop
  python3 iridium_tx_libresdr.py --cyclic                 # loop forever (Ctrl+C to stop)
  python3 iridium_tx_libresdr.py --freq 868100000 -n 8   # 8 IRA slots at 868.1 MHz
  python3 iridium_tx_libresdr.py --gain -20               # higher power (-30 dB = safer default)
  python3 iridium_tx_libresdr.py --dry-run                # show config, no TX
"""

import argparse
import sys
import os
import time
import numpy as np
from scipy import signal as sp_signal

# ── Path: resolve iridium package relative to this file ─────────────────────
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from iridium.realistic_sim import (
    generate_ira_burst,
    generate_rrc_filter,
    SYMBOL_RATE,          # 25 000 sps
    SPS,                  # 10  samples/symbol @ base rate (250 kHz)
    SAMPLE_RATE as IRA_BASE_RATE,   # 250 000 Hz
    RRC_BETA,             # 0.4
    RRC_NUM_TAPS,         # 111
    IRA_BURST_SYMS,       # 245
    IRA_PREAMBLE_SYMS,    # 64
    SUPERFRAME_S,         # 0.090 s  (90 ms between bursts)
)


# ── Hardware parameters ──────────────────────────────────────────────────────
DEFAULT_URI           = "ip:192.168.1.10"
DEFAULT_CENTER_FREQ   = 868_100_000      # 868.1 MHz ISM — safe frequency for lab tests
#                                        #  For actual Iridium field experiments: 1_626_270_000
TX_SAMPLE_RATE        = 1_000_000        # 1 MSPS — minimum stable rate for AD9363/Ethernet
TX_RF_BANDWIDTH       = 200_000          # 200 kHz — matches Iridium signal BW
DEFAULT_TX_GAIN_DB    = -30.0            # TX attenuation [dB]. Start conservatively!
#                                        #  0 dB = max power → saturation at < 0.5 m.
#                                        #  -30 dB recommended for bench tests (1-2 m, cable).

# Upsampling: IRA_BASE_RATE (250 kHz) → TX_SAMPLE_RATE (1 MHz) = exact ×4
_IRA_UPS = TX_SAMPLE_RATE // IRA_BASE_RATE   # = 4


def _make_ira_slot(rrc: np.ndarray, frame_count: int = 0,
                   sat_id: int = 47, beam_id: int = 3) -> np.ndarray:
    """
    Generate one full IRA TDMA slot (281 symbols @ 250 kHz → 1 MHz upsampled).

    Returns complex64 array ready for the AD9363 DAC.
    The slot includes preamble (64 syms, tone @ +3125 Hz), UW, and frame data.
    """
    slot_iq, _ = generate_ira_burst(rrc, sat_id=sat_id, beam_id=beam_id,
                                     frame_count=frame_count)
    # Resample 250 kHz → 1 MHz (integer ratio 4:1, no aliasing)
    upsampled = sp_signal.resample_poly(slot_iq, _IRA_UPS, 1)
    # Scale to 80 % DAC full-scale (AD9363 via pyadi-iio: |sample| ≤ 2^14)
    peak = float(np.max(np.abs(upsampled))) + 1e-12
    return (upsampled / peak * 0.8 * (2 ** 14)).astype(np.complex64)


def connect_libresdr(uri: str):
    """
    Connect to LibreSDR via pyadi-iio and return the sdr object.
    LibreSDR uses Pluto-like firmware, so adi.Pluto (or adi.ad9364) is used.
    """
    try:
        import adi
    except ImportError:
        print("[ERROR] pyadi-iio not installed.")
        print("  Install with:  pip install pyadi-iio")
        print("  Or:            pip install adi")
        sys.exit(1)

    print(f"  Connecting to LibreSDR: {uri} ...", end=" ", flush=True)
    import time as _time
    for attempt in range(3):
        try:
            # LibreSDR/AntSDR E200 firmware is compatible with the Pluto API
            sdr = adi.Pluto(uri)
            # Preventive cleanup: destroy any residual buffer from previous sessions
            try:
                sdr.tx_destroy_buffer()
            except Exception:
                pass
            print("OK")
            return sdr
        except OSError as e:
            if e.errno == 16 and attempt < 2:  # EBUSY: device or resource busy
                print(f"busy (attempt {attempt+1}/3), waiting 3s ...",
                      end=" ", flush=True)
                _time.sleep(3)
            else:
                print(f"FAILED\n[ERROR] {e}")
                print("\nCheck:")
                print("  1. LibreSDR powered and reachable:")
                host = uri.split(":", 1)[-1] if ":" in uri else uri
                print(f"     ping {host}")
                print("  2. No other process using the device:")
                print(f"     pkill -9 -f iridium")
                print("  3. iio_info -u " + uri + "  (lists IIO devices)")
                sys.exit(1)
        except Exception as e:
            print(f"FAILED\n[ERROR] {e}")
            sys.exit(1)


def configure_tx(sdr, center_freq_hz: int, gain_db: float):
    """
    Configure the AD9363 TX channel.

    Args:
        sdr: pyadi-iio object
        center_freq_hz: TX carrier frequency in Hz
        gain_db: TX attenuation in dB (range: -90 … 0 dB; lower values = less power)
    """
    sdr.sample_rate = int(TX_SAMPLE_RATE)
    sdr.tx_rf_bandwidth = int(TX_RF_BANDWIDTH)
    sdr.tx_lo = int(center_freq_hz)
    sdr.tx_hardwaregain_chan0 = float(gain_db)

    print(f"  TX configured:")
    print(f"    Centre freq:  {center_freq_hz / 1e6:.3f} MHz")
    print(f"    Sample rate:  {TX_SAMPLE_RATE / 1e6:.1f} MSPS")
    print(f"    RF bandwidth: {TX_RF_BANDWIDTH / 1e3:.0f} kHz")
    print(f"    TX gain:      {gain_db:+.0f} dB")


def transmit_once(sdr, samples: np.ndarray, num_repetitions: int = 1):
    """
    Transmit a sequence of samples N times (non-cyclic).
    Useful for sending a single burst or a limited series of frames.
    """
    for i in range(num_repetitions):
        sdr.tx(samples)
        if num_repetitions > 1:
            print(f"  Transmitted frame {i + 1}/{num_repetitions}")


def transmit_cyclic(sdr, samples: np.ndarray):
    """
    Transmit in continuous loop (cyclic buffer) until Ctrl+C.
    The hardware autonomously repeats the buffer without Python overhead.
    """
    # Preventive cleanup: destroy any buffer left open from a previous session
    try:
        sdr.tx_destroy_buffer()
    except Exception:
        pass
    sdr.tx_cyclic_buffer = True
    sdr.tx(samples)
    print("  Cyclic transmission started. Press Ctrl+C to stop.")
    try:
        while True:
            time.sleep(0.5)
    except KeyboardInterrupt:
        print("\n  Stop requested.")
    finally:
        sdr.tx_destroy_buffer()
        print("  TX buffer destroyed.")


def main():
    parser = argparse.ArgumentParser(
        description="Transmit authentic Iridium IRA bursts via LibreSDR (AD9363)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--uri",        default=DEFAULT_URI,
                        help="IIO URI of the LibreSDR")
    parser.add_argument("--freq",       type=int,   default=DEFAULT_CENTER_FREQ,
                        help="TX carrier frequency in Hz  "
                             "(default 868.1 MHz ISM; use 1626270000 for Iridium band)")
    parser.add_argument("--gain",       type=float, default=DEFAULT_TX_GAIN_DB,
                        help="TX attenuation [dB]  (0=max power, -30 safe for bench, -60 very low)")
    parser.add_argument("-n", "--num-slots", type=int, default=4,
                        help="Number of consecutive IRA slots to transmit")
    parser.add_argument("--sat-id",     type=int,   default=47,  help="Satellite ID (0-127)")
    parser.add_argument("--beam-id",    type=int,   default=3,   help="Beam ID (0-47)")
    parser.add_argument("--cyclic",     action="store_true",
                        help="Repeat buffer continuously until Ctrl+C")
    parser.add_argument("--dry-run",    action="store_true",
                        help="Print config and exit without transmitting")
    args = parser.parse_args()

    print("=" * 60)
    print("  Iridium IRA burst TX — LibreSDR (AD9363)")
    print("=" * 60)
    print(f"  Frequency   : {args.freq / 1e6:.3f} MHz")
    print(f"  Symbol rate : {SYMBOL_RATE / 1e3:.0f} ksps  (authentic Iridium)")
    print(f"  RRC β       : {RRC_BETA}  (gr-iridium reference)")
    print(f"  Preamble    : {IRA_PREAMBLE_SYMS} syms → tone at +{SYMBOL_RATE // 8} Hz")
    print(f"  Burst syms  : {IRA_BURST_SYMS}  (preamble+UW+data+tail)")
    print(f"  TDMA period : {SUPERFRAME_S * 1e3:.0f} ms / slot")
    print(f"  TX gain     : {args.gain:+.0f} dB")
    print(f"  Slots       : {args.num_slots}{'  [CYCLIC]' if args.cyclic else ''}")

    # ── Build RRC filter and generate IRA slot buffer ──────────────────────
    print(f"\n  Generating {args.num_slots} IRA slot(s)...")
    rrc = generate_rrc_filter(RRC_BETA, SPS, RRC_NUM_TAPS)

    slots = [
        _make_ira_slot(rrc, frame_count=i, sat_id=args.sat_id, beam_id=args.beam_id)
        for i in range(args.num_slots)
    ]
    # Concatenate into a single TX buffer with proper TDMA spacing
    # Each slot is one superframe long (90 ms @ 1 MSPS = 90 000 samples)
    sf_samples = int(round(SUPERFRAME_S * TX_SAMPLE_RATE))
    tx_buf = np.zeros(sf_samples * args.num_slots, dtype=np.complex64)
    for i, slot in enumerate(slots):
        n = min(len(slot), sf_samples)
        tx_buf[i * sf_samples: i * sf_samples + n] = slot[:n]

    dur_ms = len(tx_buf) / TX_SAMPLE_RATE * 1e3
    peak   = float(np.max(np.abs(tx_buf)))
    print(f"  TX buffer   : {len(tx_buf)} samples  "
          f"({dur_ms:.0f} ms)  DAC peak={peak:.0f}/16384")
    print(f"  Slot dur    : {len(slots[0]) / TX_SAMPLE_RATE * 1e3:.2f} ms "
          f"+ {(sf_samples - len(slots[0])) / TX_SAMPLE_RATE * 1e3:.2f} ms silence")

    if args.dry_run:
        print("\n  [DRY RUN]  No transmission.")
        return

    # ── Connect and transmit ────────────────────────────────────────────────
    sdr = connect_libresdr(args.uri)
    configure_tx(sdr, args.freq, args.gain)
    print()

    if args.cyclic:
        transmit_cyclic(sdr, tx_buf)
    else:
        print(f"  Transmitting {args.num_slots} slot(s)...")
        t0 = time.time()
        transmit_once(sdr, tx_buf)
        elapsed = time.time() - t0
        print(f"  Completed in {elapsed * 1e3:.0f} ms")

    print("Done.")


if __name__ == "__main__":
    main()

