#!/usr/bin/env python3
"""
iridium_tx_libresdr.py — Transmit Iridium-like bursts via LibreSDR (Zynq7020 + AD9363)

Uses pyadi-iio (same API as PlutoSDR PySDR) to configure the AD9363 and
transmit DQPSK bursts generated by iridium_burst_gen.py.

Hardware: LibreSDR (Zynq7020 + AD9363) @ ip:192.168.1.10

Dependencies:
  pip install pyadi-iio           # or: pip install adi
  sudo apt install python3-libiio  # libiio backend

Usage:
  python3 scripts/iridium_tx_libresdr.py
  python3 scripts/iridium_tx_libresdr.py --freq 433920000 --gain -40
  python3 scripts/iridium_tx_libresdr.py --uri ip:192.168.1.10 --cyclic
  python3 scripts/iridium_tx_libresdr.py --num-bursts 8 --no-channel-effects

WARNING: transmitting at 1616-1626 MHz (Iridium band) without a licence is illegal.
         Always use an authorised frequency (e.g. ISM band, RF test bench)
         or connect TX → RX with a cable + attenuator.
"""

import argparse
import sys
import os
import time
import numpy as np
from scipy import signal as sp_signal

# Import burst generator from the same scripts/ package
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from iridium_burst_gen import (
    generate_tdma_frame,
    add_channel_effects,
    SAMPLE_RATE as BURST_SAMPLE_RATE,   # 200 kHz
    SYMBOL_RATE,
    SAMPLES_PER_SYMBOL,
    RRC_BETA,
)

# ── Parametri hardware ────────────────────────────────────────────────────────
DEFAULT_URI = "ip:192.168.1.10"
DEFAULT_CENTER_FREQ = 1_626_270_000    # Iridium Ring Alert channel
TX_SAMPLE_RATE = 1_000_000             # 1 MSPS — practical minimum for AD9363 over Ethernet
TX_RF_BANDWIDTH = 200_000              # 200 kHz — matches signal bandwidth
DEFAULT_TX_GAIN_DB = -60               # TX attenuation (range: -90 … 0 dB)
                                        # Start low and increase as needed!
# Fattore di upsampling: da BURST_SAMPLE_RATE (200 kHz) a TX_SAMPLE_RATE (1 MHz)
UPSAMPLE_NUM = TX_SAMPLE_RATE          # numeratore
UPSAMPLE_DEN = BURST_SAMPLE_RATE       # denominatore
# scipy.resample_poly vuole interi ridotti ai minimi termini
from math import gcd as _gcd
_g = _gcd(UPSAMPLE_NUM, UPSAMPLE_DEN)
_UP = UPSAMPLE_NUM // _g               # 5
_DOWN = UPSAMPLE_DEN // _g             # 1


def resample_to_hw(baseband_iq: np.ndarray) -> np.ndarray:
    """
    Resample signal from BURST_SAMPLE_RATE (200 kHz) to TX_SAMPLE_RATE (1 MHz).
    Uses resample_poly which preserves phase and does not introduce aliasing.
    """
    return sp_signal.resample_poly(baseband_iq, _UP, _DOWN).astype(np.complex64)


def scale_for_dac(iq: np.ndarray) -> np.ndarray:
    """
    Scale IQ samples to the range expected by the AD9363 via pyadi-iio.
    PyaDI-IIO expects |sample| ≤ 2^14 (not ±1 as in our generated samples).
    """
    # Normalize to ±0.9 then scale to 2^14
    max_amp = np.max(np.abs(iq))
    if max_amp > 0:
        iq = iq / max_amp * 0.9
    iq *= 2 ** 14
    return iq


def connect_libresdr(uri: str):
    """
    Connect to LibreSDR via pyadi-iio and return the sdr object.
    LibreSDR uses Pluto-like firmware, so adi.Pluto (or adi.ad9364) is used.
    """
    try:
        import adi
    except ImportError:
        print("[ERROR] pyadi-iio not installed.")
        print("  Install with:  pip install pyadi-iio")
        print("  Or:            pip install adi")
        sys.exit(1)

    print(f"  Connecting to LibreSDR: {uri} ...", end=" ", flush=True)
    import time as _time
    for attempt in range(3):
        try:
            # LibreSDR/AntSDR E200 firmware is compatible with the Pluto API
            sdr = adi.Pluto(uri)
            # Preventive cleanup: destroy any residual buffer from previous sessions
            try:
                sdr.tx_destroy_buffer()
            except Exception:
                pass
            print("OK")
            return sdr
        except OSError as e:
            if e.errno == 16 and attempt < 2:  # EBUSY: device or resource busy
                print(f"busy (attempt {attempt+1}/3), waiting 3s ...",
                      end=" ", flush=True)
                _time.sleep(3)
            else:
                print(f"FAILED\n[ERROR] {e}")
                print("\nCheck:")
                print("  1. LibreSDR powered and reachable:")
                host = uri.split(":", 1)[-1] if ":" in uri else uri
                print(f"     ping {host}")
                print("  2. No other process using the device:")
                print(f"     pkill -9 -f iridium")
                print("  3. iio_info -u " + uri + "  (lists IIO devices)")
                sys.exit(1)
        except Exception as e:
            print(f"FAILED\n[ERROR] {e}")
            sys.exit(1)


def configure_tx(sdr, center_freq_hz: int, gain_db: float):
    """
    Configure the AD9363 TX channel.

    Args:
        sdr: pyadi-iio object
        center_freq_hz: TX carrier frequency in Hz
        gain_db: TX attenuation in dB (range: -90 … 0 dB; lower values = less power)
    """
    sdr.sample_rate = int(TX_SAMPLE_RATE)
    sdr.tx_rf_bandwidth = int(TX_RF_BANDWIDTH)
    sdr.tx_lo = int(center_freq_hz)
    sdr.tx_hardwaregain_chan0 = float(gain_db)

    print(f"  TX configurato:")
    print(f"    Centro:       {center_freq_hz / 1e6:.3f} MHz")
    print(f"    Sample rate:  {TX_SAMPLE_RATE / 1e6:.1f} MSPS")
    print(f"    RF bandwidth: {TX_RF_BANDWIDTH / 1e3:.0f} kHz")
    print(f"    Gain TX:      {gain_db:+.0f} dB")


def transmit_once(sdr, samples: np.ndarray, num_repetitions: int = 1):
    """
    Transmit a sequence of samples N times (non-cyclic).
    Useful for sending a single burst or a limited series of frames.
    """
    for i in range(num_repetitions):
        sdr.tx(samples)
        if num_repetitions > 1:
            print(f"  Transmitted frame {i + 1}/{num_repetitions}")


def transmit_cyclic(sdr, samples: np.ndarray):
    """
    Transmit in continuous loop (cyclic buffer) until Ctrl+C.
    The hardware autonomously repeats the buffer without Python overhead.
    """
    # Preventive cleanup: destroy any buffer left open from a previous session
    try:
        sdr.tx_destroy_buffer()
    except Exception:
        pass
    sdr.tx_cyclic_buffer = True
    sdr.tx(samples)
    print("  Cyclic transmission started. Press Ctrl+C to stop.")
    try:
        while True:
            time.sleep(0.5)
    except KeyboardInterrupt:
        print("\n  Stop requested.")
    finally:
        sdr.tx_destroy_buffer()
        print("  TX buffer destroyed.")


def main():
    parser = argparse.ArgumentParser(
        description="Transmit Iridium-like bursts via LibreSDR (AD9363) with pyadi-iio",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--uri", default=DEFAULT_URI,
                        help="IIO URI of the LibreSDR")
    parser.add_argument("--freq", type=int, default=DEFAULT_CENTER_FREQ,
                        help="TX carrier frequency in Hz")
    parser.add_argument("--gain", type=float, default=DEFAULT_TX_GAIN_DB,
                        help="TX gain in dB (range -90…0). Start low!")
    parser.add_argument("--num-bursts", type=int, default=4,
                        help="Number of bursts in the TDMA frame")
    parser.add_argument("--cyclic", action="store_true",
                        help="Continuous (cyclic) transmission until Ctrl+C")
    parser.add_argument("--repeat", type=int, default=1,
                        help="Frame repetitions (without --cyclic)")
    parser.add_argument("--fdma", action="store_true",
                        help="Simulate FDMA channels (per-burst frequency offsets)")
    parser.add_argument("--ring-alert", action="store_true",
                        help="Generate Ring Alert bursts (shorter)")
    parser.add_argument("--no-channel-effects", action="store_true",
                        help="Disable AWGN noise/offset (ideal signal)")
    parser.add_argument("--snr", type=float, default=40.0,
                        help="Simulated SNR in dB (ignored with --no-channel-effects)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Generate and show info, but do NOT transmit")
    args = parser.parse_args()

    print("=" * 60)
    print("  Iridium-like burst TX — LibreSDR (AD9363)")
    print("=" * 60)

    # ── Generate IQ frame ──────────────────────────────────────────────
    burst_types = ["ring_alert" if args.ring_alert else "data"] * args.num_bursts

    freq_offsets = None
    if args.fdma:
        channel_spacing = 41667
        freq_offsets = [
            (i - args.num_bursts // 2) * channel_spacing
            for i in range(args.num_bursts)
        ]
        print(f"  FDMA: offset = {freq_offsets} Hz")

    print(f"  Generating {args.num_bursts} bursts ({burst_types[0]})...")
    frame_iq, burst_info = generate_tdma_frame(
        num_bursts=args.num_bursts,
        burst_types=burst_types,
        freq_offsets=freq_offsets,
    )
    print(f"  Frame generated: {len(frame_iq)} samples @ {BURST_SAMPLE_RATE / 1e3:.0f} kHz "
          f"({len(frame_iq) / BURST_SAMPLE_RATE * 1e3:.1f} ms)")

    # ── Channel effects (optional) ───────────────────────────────────────────
    if not args.no_channel_effects:
        frame_iq = add_channel_effects(
            frame_iq,
            snr_db=args.snr,
            phase_offset=0.0,  # no artificial phase offset in TX
            freq_drift_hz=0.0,
        )

    # ── Resample to TX_SAMPLE_RATE ──────────────────────────────────────────
    print(f"  Resampling: {BURST_SAMPLE_RATE / 1e3:.0f} kHz → "
          f"{TX_SAMPLE_RATE / 1e6:.1f} MHz (×{_UP}/{_DOWN})...")
    tx_iq = resample_to_hw(frame_iq)

    # ── Scale for DAC ──────────────────────────────────────────────────
    tx_iq = scale_for_dac(tx_iq)
    peak = np.max(np.abs(tx_iq))
    print(f"  TX samples ready: {len(tx_iq)} @ {TX_SAMPLE_RATE / 1e6:.1f} MSPS "
          f"({len(tx_iq) / TX_SAMPLE_RATE * 1e3:.1f} ms), DAC peak={peak:.0f}/16384")

    burst_summary = []
    for info in burst_info:
        t_start = info["start_sample"] / BURST_SAMPLE_RATE * 1000
        t_end = info["end_sample"] / BURST_SAMPLE_RATE * 1000
        burst_summary.append(f"    Burst {info['index']}: {info['num_symbols']} symbols, "
                              f"{t_start:.1f}–{t_end:.1f} ms")
    print("\n".join(burst_summary))
    print()

    if args.dry_run:
        print("[DRY RUN] No transmission performed.")
        return

    # ── Connect and TX ───────────────────────────────────────────────────────
    sdr = connect_libresdr(args.uri)
    configure_tx(sdr, args.freq, args.gain)
    print()

    if args.cyclic:
        transmit_cyclic(sdr, tx_iq)
    else:
        print(f"  Transmitting {args.repeat} frame(s)...")
        t0 = time.time()
        transmit_once(sdr, tx_iq, num_repetitions=args.repeat)
        elapsed = time.time() - t0
        print(f"  Completed in {elapsed:.2f} s")

    print("Done!")


if __name__ == "__main__":
    main()
